name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Python application Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app1-python:latest ./applications/app1-python

    - name: Build Go application Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app2-go:latest ./applications/app2-go

    - name: Push Python application image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/app2-go:latest

    - name: Push Go application image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/app2-go:latest
